<?php


/**
 * This class defines the structure of the 'file' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct 31 14:46:48 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FileTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FileTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('file');
		$this->setPhpName('File');
		$this->setClassname('File');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('TYPE', 'Type', 'INTEGER', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', true, 255, null);
		$this->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', true, null, null);
		$this->addColumn('ORIGINAL', 'Original', 'VARCHAR', true, 255, null);
		$this->addColumn('WEB', 'Web', 'VARCHAR', true, 255, null);
		$this->addColumn('THUMB200', 'Thumb200', 'VARCHAR', true, 255, null);
		$this->addColumn('THUMB100', 'Thumb100', 'VARCHAR', true, 255, null);
		$this->addColumn('EXTENTION', 'Extention', 'VARCHAR', true, 255, null);
		$this->addColumn('SIZE', 'Size', 'DOUBLE', true, null, null);
		$this->addColumn('FOLDER_COVER', 'FolderCover', 'TINYINT', true, null, null);
		$this->addColumn('LAT', 'Lat', 'VARCHAR', true, 255, null);
		$this->addColumn('LNG', 'Lng', 'VARCHAR', true, 255, null);
		$this->addColumn('AVERAGE_POINT', 'AveragePoint', 'DOUBLE', true, null, null);
		$this->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'user', 'ID', true, null, null);
		$this->addForeignKey('GROUPE_ID', 'GroupeId', 'INTEGER', 'groupe', 'ID', true, null, null);
		$this->addForeignKey('FOLDER_ID', 'FolderId', 'INTEGER', 'folder', 'ID', true, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', true, null, null);
		$this->addColumn('MAIN_COLOR', 'MainColor', 'VARCHAR', false, 255, null);
		$this->addColumn('STATE', 'State', 'INTEGER', true, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', true, null, null);
		$this->addForeignKey('DISK_ID', 'DiskId', 'INTEGER', 'disk', 'ID', true, null, null);
		$this->addColumn('SOURCE', 'Source', 'VARCHAR', false, 255, null);
		$this->addForeignKey('LICENCE_ID', 'LicenceId', 'INTEGER', 'licence', 'ID', false, null, null);
		$this->addForeignKey('USAGE_DISTRIBUTION_ID', 'UsageDistributionId', 'INTEGER', 'usage_distribution', 'ID', false, null, null);
		$this->addForeignKey('USAGE_CONSTRAINT_ID', 'UsageConstraintId', 'INTEGER', 'usage_constraint', 'ID', false, null, null);
		$this->addForeignKey('USAGE_USE_ID', 'UsageUseId', 'INTEGER', 'usage_use', 'ID', false, null, null);
		$this->addForeignKey('USAGE_COMMERCIAL_ID', 'UsageCommercialId', 'INTEGER', 'usage_commercial', 'ID', false, null, null);
		$this->addForeignKey('CREATIVE_COMMONS_ID', 'CreativeCommonsId', 'INTEGER', 'creative_commons', 'ID', false, null, null);
		$this->addColumn('WIDTH', 'Width', 'INTEGER', false, null, null);
		$this->addColumn('HEIGHT', 'Height', 'INTEGER', false, null, null);
		$this->addColumn('CHECKSUM', 'Checksum', 'VARCHAR', true, 255, null);
		$this->addColumn('THUMB_MOB', 'ThumbMob', 'VARCHAR', false, 255, null);
		$this->addColumn('THUMB_MOB_W', 'ThumbMobW', 'VARCHAR', false, 255, null);
		$this->addColumn('THUMB_TAB', 'ThumbTab', 'VARCHAR', false, 255, null);
		$this->addColumn('THUMB_TAB_W', 'ThumbTabW', 'VARCHAR', false, 255, null);
		$this->addColumn('GROUPE_COVER', 'GroupeCover', 'TINYINT', true, null, null);
		$this->addColumn('THUMB400', 'Thumb400', 'VARCHAR', false, 255, null);
		$this->addColumn('THUMB400_W', 'Thumb400W', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('User', 'User', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Groupe', 'Groupe', RelationMap::MANY_TO_ONE, array('groupe_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Folder', 'Folder', RelationMap::MANY_TO_ONE, array('folder_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Disk', 'Disk', RelationMap::MANY_TO_ONE, array('disk_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Licence', 'Licence', RelationMap::MANY_TO_ONE, array('licence_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('UsageDistribution', 'UsageDistribution', RelationMap::MANY_TO_ONE, array('usage_distribution_id' => 'id', ), 'SET NULL', 'SET NULL');
    $this->addRelation('UsageConstraint', 'UsageConstraint', RelationMap::MANY_TO_ONE, array('usage_constraint_id' => 'id', ), 'SET NULL', 'SET NULL');
    $this->addRelation('UsageUse', 'UsageUse', RelationMap::MANY_TO_ONE, array('usage_use_id' => 'id', ), 'SET NULL', 'SET NULL');
    $this->addRelation('UsageCommercial', 'UsageCommercial', RelationMap::MANY_TO_ONE, array('usage_commercial_id' => 'id', ), 'SET NULL', 'SET NULL');
    $this->addRelation('CreativeCommons', 'CreativeCommons', RelationMap::MANY_TO_ONE, array('creative_commons_id' => 'id', ), 'SET NULL', 'SET NULL');
    $this->addRelation('Comment', 'Comment', RelationMap::ONE_TO_MANY, array('id' => 'file_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('FileTmp', 'FileTmp', RelationMap::ONE_TO_MANY, array('id' => 'file_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Rating', 'Rating', RelationMap::ONE_TO_MANY, array('id' => 'file_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Exif', 'Exif', RelationMap::ONE_TO_MANY, array('id' => 'file_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Iptc', 'Iptc', RelationMap::ONE_TO_MANY, array('id' => 'file_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('BasketHasContent', 'BasketHasContent', RelationMap::ONE_TO_MANY, array('id' => 'file_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('FileWaiting', 'FileWaiting', RelationMap::ONE_TO_MANY, array('id' => 'file_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('FileRelatedRelatedByFileIdTo', 'FileRelated', RelationMap::ONE_TO_MANY, array('id' => 'file_id_to', ), 'CASCADE', 'CASCADE');
    $this->addRelation('FileRelatedRelatedByFileIdFrom', 'FileRelated', RelationMap::ONE_TO_MANY, array('id' => 'file_id_from', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // FileTableMap
