<?php


/**
 * This class defines the structure of the 'module_value' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct 31 14:46:53 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ModuleValueTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ModuleValueTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('module_value');
		$this->setPhpName('ModuleValue');
		$this->setClassname('ModuleValue');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('MODULE_ID', 'ModuleId', 'INTEGER', 'module', 'ID', true, null, null);
		$this->addColumn('VALUE', 'Value', 'LONGVARCHAR', true, null, null);
		$this->addColumn('RANKING', 'Ranking', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Module', 'Module', RelationMap::MANY_TO_ONE, array('module_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('ModuleValueI18n', 'ModuleValueI18n', RelationMap::ONE_TO_MANY, array('id' => 'id', ), null, null);
    $this->addRelation('Module', 'Module', RelationMap::ONE_TO_MANY, array('id' => 'default_value', ), 'SET NULL', 'SET NULL');
    $this->addRelation('CustomerHasModule', 'CustomerHasModule', RelationMap::ONE_TO_MANY, array('id' => 'module_value_id', ), 'SET NULL', 'SET NULL');
    $this->addRelation('UserHasModule', 'UserHasModule', RelationMap::ONE_TO_MANY, array('id' => 'module_value_id', ), 'SET NULL', 'SET NULL');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_i18n' => array('i18n_table' => 'module_value_i18n', ),
		);
	} // getBehaviors()

} // ModuleValueTableMap
