<?php


/**
 * This class defines the structure of the 'permalink' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct 31 14:46:51 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PermalinkTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PermalinkTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('permalink');
		$this->setPhpName('Permalink');
		$this->setClassname('Permalink');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('TYPE', 'Type', 'INTEGER', true, null, 1);
		$this->addColumn('OBJECT_TYPE', 'ObjectType', 'INTEGER', true, null, null);
		$this->addColumn('OBJECT_ID', 'ObjectId', 'INTEGER', true, null, null);
		$this->addColumn('USER_ID', 'UserId', 'INTEGER', true, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('END_AT', 'EndAt', 'TIMESTAMP', true, null, null);
		$this->addColumn('LINK', 'Link', 'VARCHAR', true, 255, null);
		$this->addColumn('QRCODE', 'Qrcode', 'VARCHAR', true, 255, null);
		$this->addColumn('ALLOW_COMMENTS', 'AllowComments', 'BOOLEAN', true, null, null);
		$this->addColumn('FORMAT_HD', 'FormatHd', 'BOOLEAN', true, null, null);
		$this->addColumn('STATE', 'State', 'INTEGER', true, null, null);
		$this->addColumn('PASSWORD', 'Password', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('PermalinkComment', 'PermalinkComment', RelationMap::ONE_TO_MANY, array('id' => 'permalink_id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // PermalinkTableMap
