<?php


/**
 * Skeleton subclass for representing a row from the 'basket' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Aug 23 16:07:24 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Basket extends BaseBasket
{
	/*________________________________________________________________________________________________________________*/
	public function getName()
	{
		return $this->getTitle();
	}

	/*________________________________________________________________________________________________________________*/
	public function setName($name)
	{
		$this->setTitle($name);
	}

	/*________________________________________________________________________________________________________________*/
	public function __toString()
	{
		return $this->getTitle() ? $this->getTitle() : $this->getCode();
	}

	/*________________________________________________________________________________________________________________*/
	public function isEmpty()
	{
		return BasketHasContentPeer::countFiles($this->getId()) == 0 ? true : false;
	}

	/*________________________________________________________________________________________________________________*/
	public function save(PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(FilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try
		{
			if($this->isNew())
			{
				$this->setCode(BasketPeer::getCode());
				$this->setAllowComments(false);
				$this->setAllowDownloadHd(false);
			}

			$ret = parent::save($con);

			$con->commit();

			return $ret;
		}
		catch (Exception $e)
		{
			$con->rollBack();
			throw $e;
		}
	}
}
