<?php


/**
 * Skeleton subclass for performing query and update operations on the 'continent' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * mer. 25 janv. 2012 11:17:36 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ContinentPeer extends BaseContinentPeer 
{
	/*________________________________________________________________________________________________________________*/
	public static function getContinents()
	{
		$c = new Criteria();
		
		$c->addJoin(ContinentI18nPeer::ID, self::ID);
		$c->add(ContinentI18nPeer::CULTURE, sfContext::getInstance()->getUser()->getCulture());
		$c->addAscendingOrderByColumn(ContinentI18nPeer::TITLE);

		return self::doSelectWithI18n($c);
	}

	/*________________________________________________________________________________________________________________*/
	public static function referToContinent($country_ids)
	{
		$c = new Criteria();
		$continents = self::doSelect($c);

		foreach($continents as $continent)
		{
			$countries = CountryPeer::retrieveByContinentId($continent->getId());
			$idCountry = Array();

			foreach($countries as $country)
				$idCountry[] = $country->getId();

			$diff = array_diff($idCountry, $country_ids);

			if(empty($diff))
				return $continent->getTitle();
		}

		return false;
	}
}
