<?php


/**
 * Skeleton subclass for performing query and update operations on the 'creative_commons_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * mer. 01 févr. 2012 17:07:55 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CreativeCommonsI18nPeer extends BaseCreativeCommonsI18nPeer {

} // CreativeCommonsI18nPeer
