<?php


/**
 * Skeleton subclass for performing query and update operations on the 'culture' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jun 27 14:48:56 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CulturePeer extends BaseCulturePeer
{
	const __CULT_FR = 1;
	const __CULT_EN = 1;

	/*________________________________________________________________________________________________________________*/
	public static function get()
	{
		$c = new Criteria();
		$c->addAscendingOrderByColumn(CultureI18nPeer::TITLE);
		
		return self::doSelectWithI18n($c, sfContext::getInstance()->getUser()->getCulture());
	}

	/*________________________________________________________________________________________________________________*/
	public static function getInArray()
	{
		$cultures = self::get();
		$culture_array = Array();

		foreach ($cultures as $culture) {
			$culture_array[$culture->getId()] = $culture->getTitle();
		}
		
		return $culture_array;
	}

	/*________________________________________________________________________________________________________________*/
	public static function retrieveByTitle($culture)
	{
		$c = new Criteria();
		$c->addJoin(CultureI18nPeer::ID, self::ID);
		$c->add(CultureI18nPeer::TITLE, strtolower($culture));

		return self::doSelectOne($c);
	}

	/*________________________________________________________________________________________________________________*/
	public static function retrieveByCode($code)
	{
		$c = new Criteria();
		$c->addJoin(CultureI18nPeer::ID, self::ID);
		$c->add(CultureI18nPeer::CODE, strtolower($code));

		return self::doSelectOne($c);
	}
}
