<?php


/**
 * Skeleton subclass for representing a row from the 'field' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * mer. 25 juil. 2012 16:24:15 CEST
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Field extends BaseField 
{
	/*________________________________________________________________________________________________________________*/
	public function getStringType()
	{
		$temp = FieldPeer::getTypes();

		return $temp[$this->getType()];
	}
}
