<?php


/**
 * Skeleton subclass for representing a row from the 'geolocation' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * jeu. 14 févr. 2013 06:46:53 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Geolocation extends BaseGeolocation {

} // Geolocation
