<?php


/**
 * Skeleton subclass for representing a row from the 'log_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Sep  2 14:27:36 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LogI18n extends BaseLogI18n {

} // LogI18n
