<?php


/**
 * Skeleton subclass for performing query and update operations on the 'log_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * mer. 22 févr. 2012 16:28:24 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LogUserPeer extends BaseLogUserPeer 
{
	/*________________________________________________________________________________________________________________*/
	public static function setUserLog($user_id)
	{
		$log = new LogUser();
		$log->setUserId($user_id);
		$log->setRemoteAddr($_SERVER['REMOTE_ADDR']);
		$log->setUserAgent($_SERVER['HTTP_USER_AGENT']);
		$log->setUri($_SERVER['REQUEST_URI']);

		if(array_key_exists('HTTP_REFERER', $_SERVER))
			$log->setReferer($_SERVER['HTTP_REFERER']);

		$log->save();
	}
}
