<?php


/**
 * Skeleton subclass for representing a row from the 'log_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * mer. 22 févr. 2012 16:28:24 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LogUser extends BaseLogUser {

} // LogUser
