<?php


/**
 * Skeleton subclass for representing a row from the 'module_has_visibility' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * ven. 23 mars 2012 14:20:18 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ModuleHasVisibility extends BaseModuleHasVisibility {

} // ModuleHasVisibility
