<?php


/**
 * Skeleton subclass for performing query and update operations on the 'permalink_notification' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * lun. 27 févr. 2012 11:50:25 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PermalinkNotificationPeer extends BasePermalinkNotificationPeer
{
	const __ADD_COMMENT = "comment";
	const __ADD_FILE = "upload";

	/*________________________________________________________________________________________________________________*/
	public static function retrieveByPermalinkIdAndUserId($permalink_id, $user_id)
	{
		$c = new Criteria();
		
		$c->addJoin(self::USER_ID, UserPeer::ID);
		$c->add(UserPeer::STATE, UserPeer::__STATE_ACTIVE);
		$c->add(self::PERMALINK_ID, $permalink_id);
		$c->add(self::USER_ID, $user_id);

		return self::doSelectOne($c);
	}

	/*________________________________________________________________________________________________________________*/
	public static function retrieveByPermalinkId($permalink_id)
	{
		$c = new Criteria();
		
		$c->addJoin(self::USER_ID, UserPeer::ID);
		$c->add(UserPeer::STATE, UserPeer::__STATE_ACTIVE);
		$c->add(self::PERMALINK_ID, $permalink_id);

		return self::doSelect($c);
	}
}
