<?php


/**
 * Skeleton subclass for representing a row from the 'permalink_notification' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * lun. 27 févr. 2012 11:50:25 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PermalinkNotification extends BasePermalinkNotification {

} // PermalinkNotification
