<?php


/**
 * Skeleton subclass for representing a row from the 'thesaurus' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * mar. 03 juil. 2012 14:55:01 CEST
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Thesaurus extends BaseThesaurus 
{
	/*________________________________________________________________________________________________________________*/
	public function __toString()
	{
		return $this->getTitle();
	}

	/*________________________________________________________________________________________________________________*/
	public function hasChildren()
	{
		$c = new Criteria();
		$c->add(ThesaurusPeer::PARENT_ID, $this->getId());

		return ThesaurusPeer::doCount($c) > 0 ? true : false;
	}
}
