<?php


/**
 * Skeleton subclass for representing a row from the 'unit_group' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Aug 30 10:30:18 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UnitGroup extends BaseUnitGroup {
	/*________________________________________________________________________________________________________________*/
	/**
	 * Renvoie le credential.
	 *
	 * @return Role
	 */
	public function getCredential()
	{
		return RolePeer::retrieveByPK($this->getRole());
	}
}
