<?php


/**
 * Skeleton subclass for performing query and update operations on the 'usage_commercial' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * mar. 31 janv. 2012 15:30:53 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UsageCommercialPeer extends BaseUsageCommercialPeer
{
	const __ALL = 1;
	const __ALL_NO_RESALE = 2;

	/*________________________________________________________________________________________________________________*/
	public static function getCommercials()
	{
		$c = new Criteria();
		
		$c->addJoin(UsageCommercialI18nPeer::ID, self::ID);
		$c->add(UsageCommercialI18nPeer::CULTURE, sfContext::getInstance()->getUser()->getCulture());
		$c->addAscendingOrderByColumn(UsageCommercialI18nPeer::TITLE);

		return self::doSelect($c);
	}

	/*________________________________________________________________________________________________________________*/
	public static function getCommercialForFiles($file_ids)
	{
		$commercials = Array();

		foreach ($file_ids as $file_id) {
			$file = FilePeer::retrieveByPk($file_id);

			if ($file && $file->getUsageCommercialId()) {
				$commercial = self::retrieveByPk($file->getUsageCommercialId());

				if (!in_array($commercial, $commercials)) {
					$commercials[$commercial->getId()] = $commercial;
				}
			}
		}

		return $commercials;
	}

	/*________________________________________________________________________________________________________________*/
	public static function getCommercialForFolders($folder_ids)
	{
		$commercials = Array();

		foreach ($folder_ids as $folder_id) {
			$folder = FolderPeer::retrieveByPk($folder_id);

			if ($folder && $folder->getUsageCommercialId()) {
				$commercial = self::retrieveByPk($folder->getUsageCommercialId());

				if (!in_array($commercial, $commercials)) {
					$commercials[$commercial->getId()] = $commercial;
				}
			}
		}

		return $commercials;
	}
}
