<?php


/**
 * Skeleton subclass for representing a row from the 'user_has_module' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * jeu. 22 mars 2012 17:16:21 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserHasModule extends BaseUserHasModule {
	/**
	 * Get the associated Module object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Module The associated Module object.
	 * @throws     PropelException
	 */
	public function getModule(PropelPDO $con = null)
	{
		if ($this->aModule === null && ($this->module_id !== null)) {
			$this->aModule = ModulePeer::retrieveByPkI18n($this->module_id);
		}
	
		return $this->aModule;
	}
} // UserHasModule
