<?php

/**
 * Base class that represents a row from the 'module' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct 31 14:46:53 2013
 *
 * @package    lib.model.om
 */
abstract class BaseModule extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ModulePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the deactivated field.
	 * @var        boolean
	 */
	protected $deactivated;

	/**
	 * The value for the default_value field.
	 * @var        int
	 */
	protected $default_value;

	/**
	 * @var        ModuleValue
	 */
	protected $aModuleValue;

	/**
	 * @var        array ModuleValue[] Collection to store aggregation of ModuleValue objects.
	 */
	protected $collModuleValues;

	/**
	 * @var        Criteria The criteria used to select the current contents of collModuleValues.
	 */
	private $lastModuleValueCriteria = null;

	/**
	 * @var        array ModuleI18n[] Collection to store aggregation of ModuleI18n objects.
	 */
	protected $collModuleI18ns;

	/**
	 * @var        Criteria The criteria used to select the current contents of collModuleI18ns.
	 */
	private $lastModuleI18nCriteria = null;

	/**
	 * @var        array CustomerHasModule[] Collection to store aggregation of CustomerHasModule objects.
	 */
	protected $collCustomerHasModules;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCustomerHasModules.
	 */
	private $lastCustomerHasModuleCriteria = null;

	/**
	 * @var        array UserHasModule[] Collection to store aggregation of UserHasModule objects.
	 */
	protected $collUserHasModules;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserHasModules.
	 */
	private $lastUserHasModuleCriteria = null;

	/**
	 * @var        array ModuleHasVisibility[] Collection to store aggregation of ModuleHasVisibility objects.
	 */
	protected $collModuleHasVisibilitys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collModuleHasVisibilitys.
	 */
	private $lastModuleHasVisibilityCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ModulePeer';

	// symfony_i18n behavior
	
	/**
	 * @var string The value for the culture field
	 */
	protected $culture = null;
	
	/**
	 * @var array Current I18N objects
	 */
	protected $current_i18n = array();

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [deactivated] column value.
	 * 
	 * @return     boolean
	 */
	public function getDeactivated()
	{
		return $this->deactivated;
	}

	/**
	 * Get the [default_value] column value.
	 * 
	 * @return     int
	 */
	public function getDefaultValue()
	{
		return $this->default_value;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Module The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ModulePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [deactivated] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Module The current object (for fluent API support)
	 */
	public function setDeactivated($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->deactivated !== $v) {
			$this->deactivated = $v;
			$this->modifiedColumns[] = ModulePeer::DEACTIVATED;
		}

		return $this;
	} // setDeactivated()

	/**
	 * Set the value of [default_value] column.
	 * 
	 * @param      int $v new value
	 * @return     Module The current object (for fluent API support)
	 */
	public function setDefaultValue($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->default_value !== $v) {
			$this->default_value = $v;
			$this->modifiedColumns[] = ModulePeer::DEFAULT_VALUE;
		}

		if ($this->aModuleValue !== null && $this->aModuleValue->getId() !== $v) {
			$this->aModuleValue = null;
		}

		return $this;
	} // setDefaultValue()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->deactivated = ($row[$startcol + 1] !== null) ? (boolean) $row[$startcol + 1] : null;
			$this->default_value = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 3; // 3 = ModulePeer::NUM_COLUMNS - ModulePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Module object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aModuleValue !== null && $this->default_value !== $this->aModuleValue->getId()) {
			$this->aModuleValue = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ModulePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ModulePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aModuleValue = null;
			$this->collModuleValues = null;
			$this->lastModuleValueCriteria = null;

			$this->collModuleI18ns = null;
			$this->lastModuleI18nCriteria = null;

			$this->collCustomerHasModules = null;
			$this->lastCustomerHasModuleCriteria = null;

			$this->collUserHasModules = null;
			$this->lastUserHasModuleCriteria = null;

			$this->collModuleHasVisibilitys = null;
			$this->lastModuleHasVisibilityCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ModulePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseModule:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ModulePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseModule:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ModulePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseModule:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseModule:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ModulePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aModuleValue !== null) {
				if ($this->aModuleValue->isModified() || $this->aModuleValue->isNew()) {
					$affectedRows += $this->aModuleValue->save($con);
				}
				$this->setModuleValue($this->aModuleValue);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ModulePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ModulePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ModulePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collModuleValues !== null) {
				foreach ($this->collModuleValues as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collModuleI18ns !== null) {
				foreach ($this->collModuleI18ns as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCustomerHasModules !== null) {
				foreach ($this->collCustomerHasModules as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUserHasModules !== null) {
				foreach ($this->collUserHasModules as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collModuleHasVisibilitys !== null) {
				foreach ($this->collModuleHasVisibilitys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aModuleValue !== null) {
				if (!$this->aModuleValue->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aModuleValue->getValidationFailures());
				}
			}


			if (($retval = ModulePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collModuleValues !== null) {
					foreach ($this->collModuleValues as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collModuleI18ns !== null) {
					foreach ($this->collModuleI18ns as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCustomerHasModules !== null) {
					foreach ($this->collCustomerHasModules as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUserHasModules !== null) {
					foreach ($this->collUserHasModules as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collModuleHasVisibilitys !== null) {
					foreach ($this->collModuleHasVisibilitys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ModulePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getDeactivated();
				break;
			case 2:
				return $this->getDefaultValue();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ModulePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getDeactivated(),
			$keys[2] => $this->getDefaultValue(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ModulePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setDeactivated($value);
				break;
			case 2:
				$this->setDefaultValue($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ModulePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setDeactivated($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDefaultValue($arr[$keys[2]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ModulePeer::DATABASE_NAME);

		if ($this->isColumnModified(ModulePeer::ID)) $criteria->add(ModulePeer::ID, $this->id);
		if ($this->isColumnModified(ModulePeer::DEACTIVATED)) $criteria->add(ModulePeer::DEACTIVATED, $this->deactivated);
		if ($this->isColumnModified(ModulePeer::DEFAULT_VALUE)) $criteria->add(ModulePeer::DEFAULT_VALUE, $this->default_value);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ModulePeer::DATABASE_NAME);

		$criteria->add(ModulePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Module (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setDeactivated($this->deactivated);

		$copyObj->setDefaultValue($this->default_value);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getModuleValues() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addModuleValue($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getModuleI18ns() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addModuleI18n($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCustomerHasModules() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCustomerHasModule($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUserHasModules() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserHasModule($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getModuleHasVisibilitys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addModuleHasVisibility($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Module Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ModulePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ModulePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a ModuleValue object.
	 *
	 * @param      ModuleValue $v
	 * @return     Module The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setModuleValue(ModuleValue $v = null)
	{
		if ($v === null) {
			$this->setDefaultValue(NULL);
		} else {
			$this->setDefaultValue($v->getId());
		}

		$this->aModuleValue = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ModuleValue object, it will not be re-added.
		if ($v !== null) {
			$v->addModule($this);
		}

		return $this;
	}


	/**
	 * Get the associated ModuleValue object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ModuleValue The associated ModuleValue object.
	 * @throws     PropelException
	 */
	public function getModuleValue(PropelPDO $con = null)
	{
		if ($this->aModuleValue === null && ($this->default_value !== null)) {
			$this->aModuleValue = ModuleValuePeer::retrieveByPk($this->default_value);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aModuleValue->addModules($this);
			 */
		}
		return $this->aModuleValue;
	}

	/**
	 * Clears out the collModuleValues collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addModuleValues()
	 */
	public function clearModuleValues()
	{
		$this->collModuleValues = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collModuleValues collection (array).
	 *
	 * By default this just sets the collModuleValues collection to an empty array (like clearcollModuleValues());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initModuleValues()
	{
		$this->collModuleValues = array();
	}

	/**
	 * Gets an array of ModuleValue objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Module has previously been saved, it will retrieve
	 * related ModuleValues from storage. If this Module is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ModuleValue[]
	 * @throws     PropelException
	 */
	public function getModuleValues($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collModuleValues === null) {
			if ($this->isNew()) {
			   $this->collModuleValues = array();
			} else {

				$criteria->add(ModuleValuePeer::MODULE_ID, $this->id);

				ModuleValuePeer::addSelectColumns($criteria);
				$this->collModuleValues = ModuleValuePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ModuleValuePeer::MODULE_ID, $this->id);

				ModuleValuePeer::addSelectColumns($criteria);
				if (!isset($this->lastModuleValueCriteria) || !$this->lastModuleValueCriteria->equals($criteria)) {
					$this->collModuleValues = ModuleValuePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastModuleValueCriteria = $criteria;
		return $this->collModuleValues;
	}

	/**
	 * Returns the number of related ModuleValue objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ModuleValue objects.
	 * @throws     PropelException
	 */
	public function countModuleValues(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collModuleValues === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ModuleValuePeer::MODULE_ID, $this->id);

				$count = ModuleValuePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ModuleValuePeer::MODULE_ID, $this->id);

				if (!isset($this->lastModuleValueCriteria) || !$this->lastModuleValueCriteria->equals($criteria)) {
					$count = ModuleValuePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collModuleValues);
				}
			} else {
				$count = count($this->collModuleValues);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ModuleValue object to this object
	 * through the ModuleValue foreign key attribute.
	 *
	 * @param      ModuleValue $l ModuleValue
	 * @return     void
	 * @throws     PropelException
	 */
	public function addModuleValue(ModuleValue $l)
	{
		if ($this->collModuleValues === null) {
			$this->initModuleValues();
		}
		if (!in_array($l, $this->collModuleValues, true)) { // only add it if the **same** object is not already associated
			array_push($this->collModuleValues, $l);
			$l->setModule($this);
		}
	}

	/**
	 * Clears out the collModuleI18ns collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addModuleI18ns()
	 */
	public function clearModuleI18ns()
	{
		$this->collModuleI18ns = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collModuleI18ns collection (array).
	 *
	 * By default this just sets the collModuleI18ns collection to an empty array (like clearcollModuleI18ns());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initModuleI18ns()
	{
		$this->collModuleI18ns = array();
	}

	/**
	 * Gets an array of ModuleI18n objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Module has previously been saved, it will retrieve
	 * related ModuleI18ns from storage. If this Module is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ModuleI18n[]
	 * @throws     PropelException
	 */
	public function getModuleI18ns($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collModuleI18ns === null) {
			if ($this->isNew()) {
			   $this->collModuleI18ns = array();
			} else {

				$criteria->add(ModuleI18nPeer::ID, $this->id);

				ModuleI18nPeer::addSelectColumns($criteria);
				$this->collModuleI18ns = ModuleI18nPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ModuleI18nPeer::ID, $this->id);

				ModuleI18nPeer::addSelectColumns($criteria);
				if (!isset($this->lastModuleI18nCriteria) || !$this->lastModuleI18nCriteria->equals($criteria)) {
					$this->collModuleI18ns = ModuleI18nPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastModuleI18nCriteria = $criteria;
		return $this->collModuleI18ns;
	}

	/**
	 * Returns the number of related ModuleI18n objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ModuleI18n objects.
	 * @throws     PropelException
	 */
	public function countModuleI18ns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collModuleI18ns === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ModuleI18nPeer::ID, $this->id);

				$count = ModuleI18nPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ModuleI18nPeer::ID, $this->id);

				if (!isset($this->lastModuleI18nCriteria) || !$this->lastModuleI18nCriteria->equals($criteria)) {
					$count = ModuleI18nPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collModuleI18ns);
				}
			} else {
				$count = count($this->collModuleI18ns);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ModuleI18n object to this object
	 * through the ModuleI18n foreign key attribute.
	 *
	 * @param      ModuleI18n $l ModuleI18n
	 * @return     void
	 * @throws     PropelException
	 */
	public function addModuleI18n(ModuleI18n $l)
	{
		if ($this->collModuleI18ns === null) {
			$this->initModuleI18ns();
		}
		if (!in_array($l, $this->collModuleI18ns, true)) { // only add it if the **same** object is not already associated
			array_push($this->collModuleI18ns, $l);
			$l->setModule($this);
		}
	}

	/**
	 * Clears out the collCustomerHasModules collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCustomerHasModules()
	 */
	public function clearCustomerHasModules()
	{
		$this->collCustomerHasModules = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCustomerHasModules collection (array).
	 *
	 * By default this just sets the collCustomerHasModules collection to an empty array (like clearcollCustomerHasModules());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCustomerHasModules()
	{
		$this->collCustomerHasModules = array();
	}

	/**
	 * Gets an array of CustomerHasModule objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Module has previously been saved, it will retrieve
	 * related CustomerHasModules from storage. If this Module is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array CustomerHasModule[]
	 * @throws     PropelException
	 */
	public function getCustomerHasModules($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCustomerHasModules === null) {
			if ($this->isNew()) {
			   $this->collCustomerHasModules = array();
			} else {

				$criteria->add(CustomerHasModulePeer::MODULE_ID, $this->id);

				CustomerHasModulePeer::addSelectColumns($criteria);
				$this->collCustomerHasModules = CustomerHasModulePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CustomerHasModulePeer::MODULE_ID, $this->id);

				CustomerHasModulePeer::addSelectColumns($criteria);
				if (!isset($this->lastCustomerHasModuleCriteria) || !$this->lastCustomerHasModuleCriteria->equals($criteria)) {
					$this->collCustomerHasModules = CustomerHasModulePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCustomerHasModuleCriteria = $criteria;
		return $this->collCustomerHasModules;
	}

	/**
	 * Returns the number of related CustomerHasModule objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related CustomerHasModule objects.
	 * @throws     PropelException
	 */
	public function countCustomerHasModules(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCustomerHasModules === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CustomerHasModulePeer::MODULE_ID, $this->id);

				$count = CustomerHasModulePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CustomerHasModulePeer::MODULE_ID, $this->id);

				if (!isset($this->lastCustomerHasModuleCriteria) || !$this->lastCustomerHasModuleCriteria->equals($criteria)) {
					$count = CustomerHasModulePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCustomerHasModules);
				}
			} else {
				$count = count($this->collCustomerHasModules);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a CustomerHasModule object to this object
	 * through the CustomerHasModule foreign key attribute.
	 *
	 * @param      CustomerHasModule $l CustomerHasModule
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCustomerHasModule(CustomerHasModule $l)
	{
		if ($this->collCustomerHasModules === null) {
			$this->initCustomerHasModules();
		}
		if (!in_array($l, $this->collCustomerHasModules, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCustomerHasModules, $l);
			$l->setModule($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Module is new, it will return
	 * an empty collection; or if this Module has previously
	 * been saved, it will retrieve related CustomerHasModules from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Module.
	 */
	public function getCustomerHasModulesJoinCustomer($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCustomerHasModules === null) {
			if ($this->isNew()) {
				$this->collCustomerHasModules = array();
			} else {

				$criteria->add(CustomerHasModulePeer::MODULE_ID, $this->id);

				$this->collCustomerHasModules = CustomerHasModulePeer::doSelectJoinCustomer($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CustomerHasModulePeer::MODULE_ID, $this->id);

			if (!isset($this->lastCustomerHasModuleCriteria) || !$this->lastCustomerHasModuleCriteria->equals($criteria)) {
				$this->collCustomerHasModules = CustomerHasModulePeer::doSelectJoinCustomer($criteria, $con, $join_behavior);
			}
		}
		$this->lastCustomerHasModuleCriteria = $criteria;

		return $this->collCustomerHasModules;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Module is new, it will return
	 * an empty collection; or if this Module has previously
	 * been saved, it will retrieve related CustomerHasModules from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Module.
	 */
	public function getCustomerHasModulesJoinModuleValue($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCustomerHasModules === null) {
			if ($this->isNew()) {
				$this->collCustomerHasModules = array();
			} else {

				$criteria->add(CustomerHasModulePeer::MODULE_ID, $this->id);

				$this->collCustomerHasModules = CustomerHasModulePeer::doSelectJoinModuleValue($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CustomerHasModulePeer::MODULE_ID, $this->id);

			if (!isset($this->lastCustomerHasModuleCriteria) || !$this->lastCustomerHasModuleCriteria->equals($criteria)) {
				$this->collCustomerHasModules = CustomerHasModulePeer::doSelectJoinModuleValue($criteria, $con, $join_behavior);
			}
		}
		$this->lastCustomerHasModuleCriteria = $criteria;

		return $this->collCustomerHasModules;
	}

	/**
	 * Clears out the collUserHasModules collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserHasModules()
	 */
	public function clearUserHasModules()
	{
		$this->collUserHasModules = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserHasModules collection (array).
	 *
	 * By default this just sets the collUserHasModules collection to an empty array (like clearcollUserHasModules());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserHasModules()
	{
		$this->collUserHasModules = array();
	}

	/**
	 * Gets an array of UserHasModule objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Module has previously been saved, it will retrieve
	 * related UserHasModules from storage. If this Module is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserHasModule[]
	 * @throws     PropelException
	 */
	public function getUserHasModules($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserHasModules === null) {
			if ($this->isNew()) {
			   $this->collUserHasModules = array();
			} else {

				$criteria->add(UserHasModulePeer::MODULE_ID, $this->id);

				UserHasModulePeer::addSelectColumns($criteria);
				$this->collUserHasModules = UserHasModulePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserHasModulePeer::MODULE_ID, $this->id);

				UserHasModulePeer::addSelectColumns($criteria);
				if (!isset($this->lastUserHasModuleCriteria) || !$this->lastUserHasModuleCriteria->equals($criteria)) {
					$this->collUserHasModules = UserHasModulePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserHasModuleCriteria = $criteria;
		return $this->collUserHasModules;
	}

	/**
	 * Returns the number of related UserHasModule objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserHasModule objects.
	 * @throws     PropelException
	 */
	public function countUserHasModules(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserHasModules === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserHasModulePeer::MODULE_ID, $this->id);

				$count = UserHasModulePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserHasModulePeer::MODULE_ID, $this->id);

				if (!isset($this->lastUserHasModuleCriteria) || !$this->lastUserHasModuleCriteria->equals($criteria)) {
					$count = UserHasModulePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collUserHasModules);
				}
			} else {
				$count = count($this->collUserHasModules);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a UserHasModule object to this object
	 * through the UserHasModule foreign key attribute.
	 *
	 * @param      UserHasModule $l UserHasModule
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserHasModule(UserHasModule $l)
	{
		if ($this->collUserHasModules === null) {
			$this->initUserHasModules();
		}
		if (!in_array($l, $this->collUserHasModules, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserHasModules, $l);
			$l->setModule($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Module is new, it will return
	 * an empty collection; or if this Module has previously
	 * been saved, it will retrieve related UserHasModules from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Module.
	 */
	public function getUserHasModulesJoinUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserHasModules === null) {
			if ($this->isNew()) {
				$this->collUserHasModules = array();
			} else {

				$criteria->add(UserHasModulePeer::MODULE_ID, $this->id);

				$this->collUserHasModules = UserHasModulePeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserHasModulePeer::MODULE_ID, $this->id);

			if (!isset($this->lastUserHasModuleCriteria) || !$this->lastUserHasModuleCriteria->equals($criteria)) {
				$this->collUserHasModules = UserHasModulePeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserHasModuleCriteria = $criteria;

		return $this->collUserHasModules;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Module is new, it will return
	 * an empty collection; or if this Module has previously
	 * been saved, it will retrieve related UserHasModules from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Module.
	 */
	public function getUserHasModulesJoinModuleValue($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserHasModules === null) {
			if ($this->isNew()) {
				$this->collUserHasModules = array();
			} else {

				$criteria->add(UserHasModulePeer::MODULE_ID, $this->id);

				$this->collUserHasModules = UserHasModulePeer::doSelectJoinModuleValue($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserHasModulePeer::MODULE_ID, $this->id);

			if (!isset($this->lastUserHasModuleCriteria) || !$this->lastUserHasModuleCriteria->equals($criteria)) {
				$this->collUserHasModules = UserHasModulePeer::doSelectJoinModuleValue($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserHasModuleCriteria = $criteria;

		return $this->collUserHasModules;
	}

	/**
	 * Clears out the collModuleHasVisibilitys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addModuleHasVisibilitys()
	 */
	public function clearModuleHasVisibilitys()
	{
		$this->collModuleHasVisibilitys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collModuleHasVisibilitys collection (array).
	 *
	 * By default this just sets the collModuleHasVisibilitys collection to an empty array (like clearcollModuleHasVisibilitys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initModuleHasVisibilitys()
	{
		$this->collModuleHasVisibilitys = array();
	}

	/**
	 * Gets an array of ModuleHasVisibility objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Module has previously been saved, it will retrieve
	 * related ModuleHasVisibilitys from storage. If this Module is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ModuleHasVisibility[]
	 * @throws     PropelException
	 */
	public function getModuleHasVisibilitys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collModuleHasVisibilitys === null) {
			if ($this->isNew()) {
			   $this->collModuleHasVisibilitys = array();
			} else {

				$criteria->add(ModuleHasVisibilityPeer::MODULE_ID, $this->id);

				ModuleHasVisibilityPeer::addSelectColumns($criteria);
				$this->collModuleHasVisibilitys = ModuleHasVisibilityPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ModuleHasVisibilityPeer::MODULE_ID, $this->id);

				ModuleHasVisibilityPeer::addSelectColumns($criteria);
				if (!isset($this->lastModuleHasVisibilityCriteria) || !$this->lastModuleHasVisibilityCriteria->equals($criteria)) {
					$this->collModuleHasVisibilitys = ModuleHasVisibilityPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastModuleHasVisibilityCriteria = $criteria;
		return $this->collModuleHasVisibilitys;
	}

	/**
	 * Returns the number of related ModuleHasVisibility objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ModuleHasVisibility objects.
	 * @throws     PropelException
	 */
	public function countModuleHasVisibilitys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collModuleHasVisibilitys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ModuleHasVisibilityPeer::MODULE_ID, $this->id);

				$count = ModuleHasVisibilityPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ModuleHasVisibilityPeer::MODULE_ID, $this->id);

				if (!isset($this->lastModuleHasVisibilityCriteria) || !$this->lastModuleHasVisibilityCriteria->equals($criteria)) {
					$count = ModuleHasVisibilityPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collModuleHasVisibilitys);
				}
			} else {
				$count = count($this->collModuleHasVisibilitys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ModuleHasVisibility object to this object
	 * through the ModuleHasVisibility foreign key attribute.
	 *
	 * @param      ModuleHasVisibility $l ModuleHasVisibility
	 * @return     void
	 * @throws     PropelException
	 */
	public function addModuleHasVisibility(ModuleHasVisibility $l)
	{
		if ($this->collModuleHasVisibilitys === null) {
			$this->initModuleHasVisibilitys();
		}
		if (!in_array($l, $this->collModuleHasVisibilitys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collModuleHasVisibilitys, $l);
			$l->setModule($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Module is new, it will return
	 * an empty collection; or if this Module has previously
	 * been saved, it will retrieve related ModuleHasVisibilitys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Module.
	 */
	public function getModuleHasVisibilitysJoinModuleVisibility($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModulePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collModuleHasVisibilitys === null) {
			if ($this->isNew()) {
				$this->collModuleHasVisibilitys = array();
			} else {

				$criteria->add(ModuleHasVisibilityPeer::MODULE_ID, $this->id);

				$this->collModuleHasVisibilitys = ModuleHasVisibilityPeer::doSelectJoinModuleVisibility($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ModuleHasVisibilityPeer::MODULE_ID, $this->id);

			if (!isset($this->lastModuleHasVisibilityCriteria) || !$this->lastModuleHasVisibilityCriteria->equals($criteria)) {
				$this->collModuleHasVisibilitys = ModuleHasVisibilityPeer::doSelectJoinModuleVisibility($criteria, $con, $join_behavior);
			}
		}
		$this->lastModuleHasVisibilityCriteria = $criteria;

		return $this->collModuleHasVisibilitys;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collModuleValues) {
				foreach ((array) $this->collModuleValues as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collModuleI18ns) {
				foreach ((array) $this->collModuleI18ns as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCustomerHasModules) {
				foreach ((array) $this->collCustomerHasModules as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUserHasModules) {
				foreach ((array) $this->collUserHasModules as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collModuleHasVisibilitys) {
				foreach ((array) $this->collModuleHasVisibilitys as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collModuleValues = null;
		$this->collModuleI18ns = null;
		$this->collCustomerHasModules = null;
		$this->collUserHasModules = null;
		$this->collModuleHasVisibilitys = null;
			$this->aModuleValue = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseModule:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseModule::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

	// symfony_i18n behavior
	
	/**
	 * Returns the culture.
	 *
	 * @return string The culture
	 */
	public function getCulture()
	{
	  return $this->culture;
	}
	
	/**
	 * Sets the culture.
	 *
	 * @param string  The culture to set
	 *
	 * @return Module
	 */
	public function setCulture($culture)
	{
	  $this->culture = $culture;
	  return $this;
	}
	
	/**
	 * Returns the "title" value from the current {@link ModuleI18n}.
	 */
	public function getTitle($culture = null)
	{
	  return $this->getCurrentModuleI18n($culture)->getTitle();
	}
	
	/**
	 * Sets the "title" value of the current {@link ModuleI18n}.
	 *
	 * @return Module
	 */
	public function setTitle($value, $culture = null)
	{
	  $this->getCurrentModuleI18n($culture)->setTitle($value);
	  return $this;
	}
	
	/**
	 * Returns the "description" value from the current {@link ModuleI18n}.
	 */
	public function getDescription($culture = null)
	{
	  return $this->getCurrentModuleI18n($culture)->getDescription();
	}
	
	/**
	 * Sets the "description" value of the current {@link ModuleI18n}.
	 *
	 * @return Module
	 */
	public function setDescription($value, $culture = null)
	{
	  $this->getCurrentModuleI18n($culture)->setDescription($value);
	  return $this;
	}
	
	/**
	 * Returns the current translation.
	 *
	 * @return ModuleI18n
	 */
	public function getCurrentModuleI18n($culture = null)
	{
	  if (null === $culture)
	  {
	    $culture = null === $this->culture ? sfPropel::getDefaultCulture() : $this->culture;
	  }
	
	  if (!isset($this->current_i18n[$culture]))
	  {
	    $object = $this->isNew() ? null : ModuleI18nPeer::retrieveByPK($this->getPrimaryKey(), $culture);
	    if ($object)
	    {
	      $this->setModuleI18nForCulture($object, $culture);
	    }
	    else
	    {
	      $this->setModuleI18nForCulture(new ModuleI18n(), $culture);
	      $this->current_i18n[$culture]->setCulture($culture);
	    }
	  }
	
	  return $this->current_i18n[$culture];
	}
	
	/**
	 * Sets the translation object for a culture.
	 */
	public function setModuleI18nForCulture(ModuleI18n $object, $culture)
	{
	  $this->current_i18n[$culture] = $object;
	  $this->addModuleI18n($object);
	}

} // BaseModule
